"""Subclass of OVM_Frame, which is generated by wxFormBuilder."""

import wx
import OVM_UI

# Implementing OVM_Frame
class OVM_UI_Adapater( OVM_UI.OVM_Frame ):
	def __init__( self, parent ):
		OVM_UI.OVM_Frame.__init__( self, parent )

